#!/usr/bin/env bash
set -euo pipefail

home="${HOME:-/tmp}"
path="${PATH:-/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin}"
docker_config="${DOCKER_CONFIG:-$home/.docker}"
docker_host="${DOCKER_HOST:-}"
docker_context="${DOCKER_CONTEXT:-}"

exec env -i \
  PATH="$path" \
  HOME="$home" \
  DOCKER_CONFIG="$docker_config" \
  DOCKER_HOST="$docker_host" \
  DOCKER_CONTEXT="$docker_context" \
  COURSE_GATEWAY_PORT="${COURSE_GATEWAY_PORT:-8080}" \
  COURSE_TEST_PROFILE="${COURSE_TEST_PROFILE:-1}" \
  COMPOSE_PARALLEL_LIMIT="${COMPOSE_PARALLEL_LIMIT:-2}" \
  COURSE_JWT_ISSUER="${COURSE_JWT_ISSUER:-}" \
  COURSE_JWT_AUDIENCE="${COURSE_JWT_AUDIENCE:-}" \
  COURSE_JWT_SIGNING_KEY="${COURSE_JWT_SIGNING_KEY:-}" \
  COURSE_POSTGRES_PASSWORD="${COURSE_POSTGRES_PASSWORD:-}" \
  COURSE_MIGRATOR_PASSWORD="${COURSE_MIGRATOR_PASSWORD:-}" \
  COURSE_PUBLISHER_PASSWORD="${COURSE_PUBLISHER_PASSWORD:-}" \
  COURSE_RUNTIME_PASSWORD="${COURSE_RUNTIME_PASSWORD:-}" \
  COURSE_WORKER_PASSWORD="${COURSE_WORKER_PASSWORD:-}" \
  COURSE_OUTBOX_PASSWORD="${COURSE_OUTBOX_PASSWORD:-}" \
  COURSE_INBOX_PASSWORD="${COURSE_INBOX_PASSWORD:-}" \
  COURSE_AUTOCHECK_PASSWORD="${COURSE_AUTOCHECK_PASSWORD:-}" \
  PROVIDER_URL="${PROVIDER_URL:-}" \
  OUTBOX_OWNER="${OUTBOX_OWNER:-}" \
  OUTBOX_OWNER_B="${OUTBOX_OWNER_B:-}" \
  COURSE_PROVIDER_TIMEOUT_MS="${COURSE_PROVIDER_TIMEOUT_MS:-}" \
  COURSE_OUTBOX_MAX_ATTEMPTS="${COURSE_OUTBOX_MAX_ATTEMPTS:-}" \
  COURSE_OUTBOX_BACKOFF_BASE_MS="${COURSE_OUTBOX_BACKOFF_BASE_MS:-}" \
  COURSE_OUTBOX_BACKOFF_MAX_MS="${COURSE_OUTBOX_BACKOFF_MAX_MS:-}" \
  COURSE_OUTBOX_JITTER_MAX_MS="${COURSE_OUTBOX_JITTER_MAX_MS:-}" \
  COURSE_OUTBOX_LEASE_MS="${COURSE_OUTBOX_LEASE_MS:-}" \
  COURSE_OUTBOX_POLL_MS="${COURSE_OUTBOX_POLL_MS:-}" \
  COURSE_INBOX_POLL_MS="${COURSE_INBOX_POLL_MS:-}" \
  COURSE_JOB_LEASE_MS="${COURSE_JOB_LEASE_MS:-}" \
  COURSE_WORKER_POLL_MS="${COURSE_WORKER_POLL_MS:-}" \
  COURSE_FAILPOINT="${COURSE_FAILPOINT:-}" \
  PROVIDER_CALLBACK_CAPABILITY="${PROVIDER_CALLBACK_CAPABILITY:-}" \
  PROVIDER_CALLBACK_TOKEN="${PROVIDER_CALLBACK_TOKEN:-}" \
  PROVIDER_HMAC_SECRET="${PROVIDER_HMAC_SECRET:-}" \
  RECEIPT_API_URL="${RECEIPT_API_URL:-}" \
  PROVIDER_AUDIT_TOKEN="${PROVIDER_AUDIT_TOKEN:-}" \
  COMPOSE_DISABLE_ENV_FILE=1 \
  docker compose "$@"
